# Site settings
title: yicheng.blog()
email: zhangyicheng1234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Good programming is 1% sweat and 99% coffee.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.zyceeit.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  lancevalour

# Build settings
markdown: kramdown
